# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-14 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_usermovies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovies',
            name='img',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
