# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181220_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovies',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
