# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_usermovies_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('views', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermovies',
            name='name',
        ),
    ]
