# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-25 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20181224_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies_views',
        ),
    ]
