# Generated by Django 2.1.1 on 2019-06-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_userrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
