# Generated by Django 2.1.1 on 2019-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_delete_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('span', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
