# Generated by Django 2.1.1 on 2019-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='user_name',
            field=models.CharField(max_length=128),
        ),
    ]
