# Generated by Django 2.1.1 on 2019-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_sensitiveword'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesClassicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('grenre', models.CharField(max_length=50)),
            ],
        ),
    ]
