# Generated by Django 2.1.1 on 2019-06-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_moviesclassicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesNewestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('xq_urlname', models.CharField(max_length=100)),
            ],
        ),
    ]
