"""
Django settings for login_site project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import pymysql         # 一定要添加这两行！
pymysql.install_as_MySQLdb()
from django.conf import settings

INNER_IP = '172.27.0.4:3306'
OUTER_IP = '45.40.250.238'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w7gw*xaj(w_g0-eaow4wfg8mop#2r+#9=roll3nzo3jph&-h-8'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = False

#'127.0.0.1 ','localhost ','172.27.0.2 '
ALLOWED_HOSTS = [OUTER_IP,'127.0.0.1 ','localhost ']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'login_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'login_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'login_python',        #数据库名字
        'USER': 'root',          #账号
        'PASSWORD': '20161120108',      #密码
        'HOST': INNER_IP,    #IP
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
 ]
MEDIA_ROOT=os.path.join(BASE_DIR,'static/css','static/base','static/404','static/fonts',
                        'static/ionicons','static/js','static/jwplayer','static/lazyload',
                        'static/ueditor','static/video','static/1-index-animation','static/pics')
# STATIC_ROOT = os.path.join(os.path.dirname(__file__),'static')
# STATICFILES_DIRS = (
#     ('static/css',os.path.join(STATIC_ROOT,'css').replace('\\','/') ),
#     ('static/js',os.path.join(STATIC_ROOT,'js').replace('\\','/') ),
#     ('static/main_banner',os.path.join(STATIC_ROOT,'jpg').replace('\\','/') ),
#     ('static/upload',os.path.join(STATIC_ROOT,'upload').replace('\\','/') ),
# )


EMAIL_USE_SSL = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465  # 或者 465/587是设置了 SSL 加密方式
# 发送邮件的邮箱
EMAIL_HOST_USER = '1205628156@qq.com'
# 在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'qejuiceztuyqjghe'  # 如果重新设置了新的授权码,直接使用最新的授权码即可
EMAIL_FROM = '二向箔有限公司'
CONFIRM_DAYS = 7


